import * as vscode from 'vscode'
import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
import { execFileSync } from 'child_process'
import { findExecutable, loginShell } from './shellEnv.js'

/**
 * A private tmux server that hosts every Claude session, so the panel only ever
 * needs one terminal: the VS Code terminal is just an attached client, and
 * switching sessions detaches one client and attaches another while every
 * `claude` process keeps running in the background.
 *
 * Everything here is scoped to our own socket (`-L herocode`) and our own config
 * file — the user's `~/.tmux.conf`, key bindings and default socket are never
 * touched, and a `tmux` the user is running for their own work is invisible to us.
 */

/** Socket name. Namespaced so we can never collide with the user's own server. */
const SOCKET = 'herocode'

/**
 * tmux resolves `-L <name>` under `$TMUX_TMPDIR` (else `/tmp`). The extension
 * host and an integrated terminal can genuinely disagree on that variable, which
 * would put our queries and our clients on two different sockets — so we pin it
 * on both sides rather than trusting whatever each process inherited.
 */
const TMUX_TMPDIR = '/tmp'

/** `window-size latest` and `%if` conditionals both predate this. */
const MIN_VERSION = 3.0

/** tmux session name for a Claude session id. */
function tmuxName(sessionId: string): string {
  return `hero-${sessionId}`
}

/**
 * `=` forces an exact match. Without it tmux falls back to prefix and then glob
 * matching on the target, so a stray metacharacter could fan out to sessions we
 * never meant to touch.
 */
function target(sessionId: string): string {
  return `=${tmuxName(sessionId)}`
}

/**
 * The same exact match as a *pane* target. `send-keys` resolves `-t` as a pane,
 * which rejects a bare `=name`; the trailing colon makes it "this session's
 * current window and pane" while keeping the exact-match semantics.
 */
function paneTarget(sessionId: string): string {
  return `${target(sessionId)}:`
}

let binary: string | undefined
let confPath: string | undefined
let probed = false

/**
 * Set once when tmux itself fails at runtime (bad socket dir, config error,
 * version skew we didn't catch). Demotes the rest of the window to one terminal
 * per session rather than leaving the user with terminals that die on open.
 */
let disabled = false

export function disableTmux(): void {
  disabled = true
}

/** Whether the tmux strategy should be used for the next open. */
export function tmuxReady(): boolean {
  return !disabled && !!binary && !!confPath && configuredOn()
}

/** The `heroCode.terminalMultiplexer` setting, read live so it needs no reload. */
function configuredOn(): boolean {
  return vscode.workspace.getConfiguration('heroCode').get<string>('terminalMultiplexer') !== 'off'
}

/**
 * Resolve the tmux binary and write our config file. Safe to call more than
 * once; the expensive login-shell probe inside `findExecutable` is memoized.
 * Windows has no tmux, so we never probe there.
 */
export function initTmux(context: vscode.ExtensionContext): void {
  if (probed) {
    return
  }
  probed = true
  if (process.platform === 'win32') {
    return
  }

  const configured = vscode.workspace.getConfiguration('heroCode').get<string>('tmuxPath')?.trim()
  const found = configured || findExecutable('tmux', [
    '/opt/homebrew/bin/tmux',
    '/usr/local/bin/tmux',
    '/usr/bin/tmux',
    '/bin/tmux',
    path.join(os.homedir(), '.local', 'bin', 'tmux'),
  ])
  if (!found || !versionOk(found)) {
    return
  }

  const conf = writeConfig(context)
  if (!conf) {
    return
  }
  binary = found
  confPath = conf

  // `-f` is only read when the *server* starts, so a server left over from a
  // previous window would still be running an older config. Re-source it.
  if (serverRunning()) {
    run(['source-file', conf])
  }
}

/** Require tmux >= 3.0; older builds lack `window-size` and `%if`. */
function versionOk(bin: string): boolean {
  try {
    const out = execFileSync(bin, ['-V'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] })
    const match = /tmux (\d+)\.(\d+)/.exec(out)
    if (!match) {
      return false
    }
    return Number(`${match[1]}.${match[2]}`) >= MIN_VERSION
  } catch {
    return false
  }
}

/**
 * Our tmux configuration, written fresh on every activation so an extension
 * update always ships its own settings. It is passed with `-f`, which means the
 * user's `~/.tmux.conf` is deliberately NOT loaded — this server exists to be
 * invisible, not to be configurable.
 */
const CONFIG = `# Generated by the Hero Code extension. Edits will be overwritten.
# This is a private tmux server (-L ${SOCKET}); your own ~/.tmux.conf is not loaded.

# --- invisibility: no status bar, no prefix key stealing Claude's input -------
set -g prefix None
set -g prefix2 None
set -g status off
set -g set-titles off
setw -g allow-rename off
setw -g automatic-rename off

# --- lifetime ----------------------------------------------------------------
# Closing the VS Code terminal only SIGHUPs the client, and an unattached
# session is left orphaned rather than reaped — that is what lets a session keep
# working after you switch away from it.
set -g destroy-unattached off
# So kill-session closes the attached client cleanly instead of stranding it.
set -g detach-on-destroy on
# Last session gone -> server exits and cleans up its socket.
set -s exit-empty on

# --- sizing ------------------------------------------------------------------
# The pane follows the most recently attached client, which is the only client
# we ever have. (aggressive-resize is explicitly poor for interactive shells.)
set -g window-size latest
setw -g aggressive-resize off

# --- fidelity for the Claude TUI ---------------------------------------------
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g set-clipboard on
set -g focus-events on
set -s escape-time 0
set -g history-limit 50000
# Required: without it tmux sits on the alternate screen and VS Code turns the
# mouse wheel into Up/Down arrows, which Claude reads as prompt-history
# navigation. Cost: native text selection needs Shift held down.
set -g mouse on
setw -g mode-keys emacs
%if #{>=:#{version},3.2}
set -as terminal-features ",xterm-256color:RGB"
set -g allow-passthrough on
%endif

# --- environment refreshed from the attaching VS Code terminal ---------------
# Applied on create and on every re-attach, so a new pane always sees the
# current window's IDE integration and git askpass wiring. TERM is deliberately
# absent: tmux owns it inside the pane.
set -g update-environment "PATH LANG LC_ALL LC_CTYPE COLORTERM TERM_PROGRAM TERM_PROGRAM_VERSION VSCODE_IPC_HOOK_CLI VSCODE_GIT_IPC_HANDLE VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_MAIN VSCODE_GIT_ASKPASS_EXTRA_ARGS GIT_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION DISPLAY"
`

function writeConfig(context: vscode.ExtensionContext): string | undefined {
  try {
    const dir = context.globalStorageUri.fsPath
    fs.mkdirSync(dir, { recursive: true })
    const file = path.join(dir, 'tmux.conf')
    fs.writeFileSync(file, CONFIG, 'utf8')
    return file
  } catch {
    return undefined
  }
}

/** Leading args every invocation shares. Harmless when the server is already up. */
function base(): string[] {
  return ['-L', SOCKET, '-f', confPath as string]
}

/** Run a tmux command, swallowing failures — every caller has a safe default. */
function run(args: string[]): string | undefined {
  if (!binary || !confPath) {
    return undefined
  }
  try {
    return execFileSync(binary, [...base(), ...args], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
      env: { ...process.env, TMUX_TMPDIR },
    })
  } catch {
    return undefined
  }
}

/** Neither this nor `listSessions` starts a server; both just fail if none runs. */
function serverRunning(): boolean {
  return run(['list-sessions', '-F', '#{session_name}']) !== undefined
}

export interface TmuxSession {
  /** Whether a client is currently viewing this session. */
  attached: boolean
  /**
   * The pane's foreground command — `node` while Claude runs, a shell name once
   * it has exited. The cheapest reliable "is this session still doing anything"
   * signal, and unlike Claude's pid registry it needs no launch-id/live-id
   * reconciliation.
   */
  command: string
}

/** Our live tmux sessions, keyed by Claude session id. */
export function listSessions(): Map<string, TmuxSession> {
  const result = new Map<string, TmuxSession>()
  const out = run(['list-sessions', '-F', '#{session_name}\t#{session_attached}\t#{pane_current_command}'])
  if (!out) {
    return result
  }
  for (const line of out.split('\n')) {
    const [name, attached, command] = line.split('\t')
    if (name?.startsWith('hero-')) {
      result.set(name.slice('hero-'.length), { attached: attached !== '0', command: command ?? '' })
    }
  }
  return result
}

export function hasSession(sessionId: string): boolean {
  return run(['has-session', '-t', target(sessionId)]) !== undefined
}

export function killSession(sessionId: string): void {
  run(['kill-session', '-t', target(sessionId)])
}

/**
 * Type `text` into a session's pane without submitting it. Works whether or not
 * the session is currently attached, which is how a mention can land in a
 * session that isn't the one on screen.
 */
export function sendKeys(sessionId: string, text: string): boolean {
  // `-l` sends the text literally (no key-name lookup); `--` stops tmux reading
  // a leading `-` in the text as a flag.
  return run(['send-keys', '-t', paneTarget(sessionId), '-l', '--', text]) !== undefined
}

/** Single-quote for the shell command we hand to tmux. */
function sq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

/**
 * Argv for the VS Code terminal itself.
 *
 * `new-session -A` attaches when `hero-<id>` already exists and creates it
 * otherwise, so one argv covers both paths; `-D` detaches any other client, which
 * is what enforces "exactly one client per session".
 *
 * Crucially the *terminal* runs this rather than the extension host: a tmux pane
 * is a child of the tmux server, whose environment is a snapshot of whoever
 * started it. Started from a terminal, panes inherit everything VS Code injects
 * into terminals but not into the host — `TERM_PROGRAM=vscode` (which Claude's
 * IDE integration keys off), `VSCODE_IPC_HOOK_CLI`, the git askpass wiring, and
 * every other extension's environment contributions. Started from the host, all
 * of that would be silently missing from every session, forever.
 *
 * `-c` and the command are only consulted when the session is created.
 */
export function attachArgs(sessionId: string, cwd: string, claudeCmd: string): string[] {
  const shell = loginShell()
  // tmux stamps its own `TERM_PROGRAM=tmux` / `TERM_PROGRAM_VERSION` into every
  // pane, overriding the inherited values even though its session environment
  // records them correctly — which would hide VS Code from anything that sniffs
  // those (Claude's IDE integration among them). The pane is launched from a
  // VS Code terminal by construction, so put the truth back.
  const ide = `export TERM_PROGRAM=vscode TERM_PROGRAM_VERSION=${sq(vscode.version)}`
  // `-lic` is login + interactive, so the same rc files a VS Code terminal
  // sources are sourced here and `claude` resolves on PATH exactly as it does
  // today. When claude exits we leave a live shell behind, matching the old
  // `sendText` behaviour rather than yanking the pane away.
  const inner = `${ide}; ${claudeCmd}; exec ${sq(shell)} -l`
  return [
    ...base(),
    'new-session',
    '-A',
    '-D',
    '-s', tmuxName(sessionId),
    '-c', cwd,
    `exec ${sq(shell)} -lic ${sq(inner)}`,
  ]
}

export function tmuxBinary(): string | undefined {
  return binary
}

/**
 * Environment overrides for the attach terminal. `TMUX` is the important one:
 * if VS Code was launched from inside a tmux pane (`code .`), it propagates
 * `TMUX` into every terminal and tmux then refuses to attach ("sessions should
 * be nested with care"). Our server is a different socket entirely, so clear it.
 */
export function terminalEnv(): Record<string, string | null> {
  return { TMUX: null, TMUX_PANE: null, TMUX_TMPDIR }
}
